# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd503e0967bb364ccd7856714e03fe643884357ec7efccd1b55c33c81152f9411c52bbb369df551b18c8f9e358b828c92bec7ac46b650649d64bbaf16494cad8

test:
  secret_key_base: 9c389dbada56e509c920c34c45e1d9cbc873642ffe6596249b4ab0b94b93dcc4411c924f9b4e02f1d74b0f2a9bcecae5de6e91188d9112e97537099ee5523e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
